# Generated by Django 5.0.3 on 2024-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
