# Generated by Django 5.0.3 on 2024-05-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destinition', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
