# Generated by Django 5.0.3 on 2024-05-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_flight_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('route_id', models.IntegerField()),
                ('class_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
