# Generated by Django 5.0.3 on 2024-05-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
